### ISSUE TITLE
GH Actions script does not Notify Proton of a terraform apply failure 

### ISSUE THREAD

**Issue by mreferre** [aws-samples/aws-proton-terraform-github-actions-sample#18]
Upon a failure of a terraform apply, the GH Actions script exits without notifying Proton of the failure. This is a view of the run:

![image](https://user-images.githubusercontent.com/4123965/159904480-69d9195f-9098-4882-8abd-e61bc8feebfe.png)
 
The script never gets to the Notify Proton stage. 

This is a snippet of the terraform apply failure (if of interest): 

```
Warning: Experimental feature "module_variable_optional_attrs" is active
│ 
│   on .terraform/modules/aws-eks-accelerator-for-terraform/modules/launch-templates/locals.tf line 4, in terraform:
│    4:   experiments = [module_variable_optional_attrs]
│ 
│ Experimental features are subject to breaking changes in future minor or
│ patch releases, based on feedback.
│ 
│ If you have feedback on the design of this feature, please open a GitHub
│ issue to discuss it.
│ 
│ (and 18 more similar warnings elsewhere)
╵
╷
│ Error: failed creating IAM Role (aws-preprod-dev-eks-cluster-role): EntityAlreadyExists: Role with name aws-preprod-dev-eks-cluster-role already exists.
│ 	status code: 409, request id: 957a148c-2189-4a7a-a1fa-ab44ac11e1e6
│ 
│   with module.aws-eks-accelerator-for-terraform.module.aws_eks.aws_iam_role.cluster[0],
│   on .terraform/modules/aws-eks-accelerator-for-terraform.aws_eks/main.tf line 128, in resource "aws_iam_role" "cluster":
│  128: resource "aws_iam_role" "cluster" {
│ 
╵
╷
│ Error: error creating KMS Alias (alias/aws-preprod-dev-eks): AlreadyExistsException: An alias with the name arn:aws:kms:us-west-2:***:alias/aws-preprod-dev-eks already exists
│ 
│   with module.aws-eks-accelerator-for-terraform.module.kms[0].aws_kms_alias.this,
│   on .terraform/modules/aws-eks-accelerator-for-terraform/modules/aws-kms/main.tf line 29, in resource "aws_kms_alias" "this":
│   29: resource "aws_kms_alias" "this" {
│ 
╵
Error: Process completed with exit code 1.
``` 

These are known issues that are being addressed in the template. The expectation is that the GH Actions would be able to get to the Notify Proton stage and inform Proton that the deployment failed. Right now the Proton deployment remains in the `in progress` state indefinitely.

**Comment by mreferre** [comment]
The same problem occurs when deleting an environment (which triggers a `terraform destroy`) when the destroy fails to complete: 

![image](https://user-images.githubusercontent.com/4123965/159919784-732eb33b-cceb-41da-932f-5cdc123ba71e.png)

In this case there is a failure in the destroy command (due to issues in the template) and the script doesn't get to the Notify step to tell Proton the delete did not succeed. As a matter of fact the environment has already long gone from the Proton console so not sure what the notify would produce (will the environment be shown again in the Proton console with a state that suggests the delete was unsuccessful?)

**Comment by awishn02** [comment]
this has been resolved

https://github.com/aws-samples/aws-proton-terraform-github-actions-sample/commit/434ecb632f8510f9a56efc115d1c61a5f12de127
